{% set name = "opentofu" %}
{% set version = "1.10.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/opentofu/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: efa95ba022d05a4cdc983d06007f389bd3ff50557b58309b9a22af52292a589a
  - url: https://raw.githubusercontent.com/jmespath/go-jmespath/b89213a6ec69212a244ef0d07d893bef7f2d9091/LICENSE
    sha256: e4855d38fa4a5c43945b62f0731836851d055bc200f42631f0854e75fdefe77c
    fn: LICENSE-jmespath

build:
  number: 0
  script:
    - pushd cmd/tofu  # [not win]
    - go build -v -ldflags "-w -s -X 'github.com/opentofu/opentofu/version.dev=no'" -o $PREFIX/bin/tofu  # [not win]
    - cd cmd\tofu  # [win]
    - go build -v -ldflags "-w -s -X 'github.com/opentofu/opentofu/version.dev=no'" -o %LIBRARY_PREFIX%\bin\tofu.exe  # [win]
    - go-licenses save . --save_path=../../license-files \
        --ignore github.com/opentofu/opentofu \
        --ignore github.com/jmespath/go-jmespath
requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - tofu -v

about:
  home: https://www.opentofu.org
  license: MPL-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: OpenTofu lets you declaratively manage your cloud infrastructure.
  dev_url: https://github.com/opentofu/opentofu

extra:
  recipe-maintainers:
    - xhochy
    - nick-harmening
